### ISSUE TITLE
Allow override of edition choice through environment variable 

### ISSUE THREAD

**Issue by damonmaria** [bevry/editions#10]
It would be useful to be able to blacklist syntaxes through environment variables. For example:

`SYNTAX_BLACKLIST=esnext,let`

I am having trouble with the Bevry sortobject package when run inside [Wallaby](https://wallabyjs.com/). It is an intermittent problem and I can't create a useful test case. The problem arises when the `source` directory / `esnext` edition is used and while the require must have worked first time, later on it fails. I suspect Wallaby is doing some require tricks that Bevry editions can't cope with. I would like to force the `es2015` edition in this environment.

**Comment by balupton** [comment]
@damonmaria this is a good idea, however I have reservations for anything that could change behaviour for other packages that aren't problematic

To best address this, is there any error messages that you are getting? Maybe I can improve other parts of the editions code. Alternatively, as a last workaround, perhaps it can be something like `EDITIONS_SYNTAX_BLACKLIST_SORTOBJECT=esnext`

**Comment by damonmaria** [comment]
Agree that it's a bit kludgey, and hides rather than solves the base problem. 

All I see is a compilation error at a `let` variable definition in sortobject. 

So are you suggesting with `EDITIONS_SYNTAX_BLACKLIST_SORTOBJECT ` that the sortobject package would consume this environment variable, or that editions would scan for any environment variables prefixed by `EDITIONS_SYNTAX_BLACKLIST_*`? My thought is the later would be the way to go, but scoped packages might be tricky with the `@` in the package name.

**Comment by balupton** [comment]
> All I see is a compilation error at a let variable definition in sortobject.

Would you be able to provide the full error log, or as much as possible?


> My thought is the later would be the way to go, but scoped packages might be tricky with the @ in the package name.


The latter. Good point, will need to do a regex replace.

**Comment by damonmaria** [comment]
Sorry for the delay. Error log from Wallaby with `debug: true` in Wallaby config:

```
Runtime error: 

Runtime error: /Users/damon/development/mindhive/inspector-gadget/node_modules/sortobject/source/index.js:5

Runtime error: 		for ( let i = 0; i < obj.length; ++i ) {
		          ^

Sun, 03 Jul 2016 04:37:43 GMT wallaby:workers Sandbox (active) [1pwem] error: 
Sun, 03 Jul 2016 04:37:43 GMT wallaby:workers Failed to map the stack to user code, entry message: , stack: 

Sun, 03 Jul 2016 04:37:43 GMT wallaby:workers Sandbox (active) [1pwem] error: /Users/damon/development/mindhive/inspector-gadget/node_modules/sortobject/source/index.js:5
Sun, 03 Jul 2016 04:37:43 GMT wallaby:workers Failed to map the stack to user code, entry message: /Users/damon/development/mindhive/inspector-gadget/node_modules/sortobject/source/index.js:5, stack: /Users/damon/development/mindhive/inspector-gadget/node_modules/sortobject/source/index.js:5

Sun, 03 Jul 2016 04:37:43 GMT wallaby:workers Sandbox (active) [1pwem] error: 		for ( let i = 0; i < obj.length; ++i ) {
Sun, 03 Jul 2016 04:37:43 GMT wallaby:workers Failed to map the stack to user code, entry message: 		for ( let i = 0; i < obj.length; ++i ) {, stack: 		for ( let i = 0; i < obj.length; ++i ) {
		          ^

Runtime error: 
```

Without the `Runtime error:` prefix on the log line the `^` caret points to the `i` in `let i`.

**Comment by balupton** [comment]
v1.2.0 now has the foundation for accomplishing this

**Comment by balupton** [comment]
Added to v1.3.0. Usage `EDITIONS_SYNTAX_BLACKLIST=esnext,blah,bleh`
