### ISSUE TITLE
Shorter repository description needed

### ISSUE THREAD

**Issue by zdroid** [bevry/editions#18]
> Editions are the best way to produce and consume the JavaScript packages you care about. With editions you can produce packages beautifully, and consume packages perfectly.

The repository description is a bit too long. It turned out that people don't like repositories with long descriptions, because they may be misleading. How about this:

> :package: The best way to produce and consume the JavaScript packages you care about.

(notice the emoji)

It looks like a good headline to me. Thoughts?

**Comment by balupton** [comment]
Seems nifty, and it's just a shortened version of the current description anyway.

What's the source for:

> It turned out that people don't like repositories with long descriptions, because they may be misleading.

Curious about the rising use of emojis in package names, it seems a gimmick no?

**Comment by zdroid** [comment]
@balupton The source of that is a psychological research done and being repeated often about people more likely to read a newspaper text with shorter, but cleaner description instead of the one with longer and confusing description.

About emojis — people like images. Especially emoticons. So yeah, you'll get more attention if you put an emoji on the beggining of repository description.

**Comment by balupton** [comment]
Okie, lets give it a go!

**Comment by balupton** [comment]
Okay applied to the repo description. Should we update the packages description too, as the package is the autoloader, so seems we should say it is the autoloader for the standard. Not sure how we do this.

**Comment by zdroid** [comment]
Awesome :tada:.

About updating the package description, do it (as long as it does no harm).
