### ISSUE TITLE
when i use the 'getmac' , errors happen

### ISSUE THREAD

**Issue by taeyeat** [bevry/editions#21]
var mac = require("getmac");
when i use 'getmac' , errors occurs , it say 

Error: There are no suitable editions for this environment:
opts: { cwd: 'E:\\zbot\\app\\node_modules\\_getmac@1.4.0@getmac',
  package: 'getmac' }

'enditions' and 'extract-opts' are exist , and please tell me what happened here
Thanks.

**Comment by balupton** [comment]
what is your windows version, and what is your node.js version?

**Comment by taeyeat** [comment]
windows10 the latest update , i'm not sure , and nodejs version is v9.4.0 @balupton

**Comment by taeyeat** [comment]
i use in two project , and one is available , one is error , and use the same code ,  i'm confuse .

**Comment by balupton** [comment]
v2 of editions, which has been published, will provide way better information when these things occur. It just needs to make its way down into the ecosystem.
