### ISSUE TITLE
semver dependency

### ISSUE THREAD

**Issue by jdiamond** [bevry/editions#91]
In 3.11.0, semver moved from dependencies to devDependencies so is failing to import when I use a module that depends on editions in a Docker image that only contains production dependencies.

**Comment by balupton** [comment]
Thanks, will fix tomorrow.

**Comment by balupton** [comment]
seems it has been reverted

**Comment by balupton** [comment]
looking into it now

**Comment by balupton** [comment]
fixed in v3.15.0 - sorry again! - seems that I fixed it in boundation, but then the routine automated sweep was using an old version of boundation - I'll check in the future on automated sweeps that this doesn't happen again
